### PR TITLE
[implements #6899] Update mongo drivers to latest version 3.5.5

### PR DESCRIPTION
**Pull request by Josebaseba**
Tested with mongo 3.6, 4.0 and 4.2 and with no breaking changes for the current adapter.

Related with https://github.com/balderdashy/sails/issues/6899

EDIT: All the tests are passing on my machine with remote atlas dbs, the timeout error that appveyor returns it's related with the WATERLINE_ADAPTER_TESTS_URL that you've set internally.

### CODE REVIEW

**Comment by Josebaseba** [comment]
@johnabrams7 I found out a perfomance issue on production, under a big load of usage. It might be a memory leak, I'll work on it and I'll keep you updated.

**Comment by MikeLindenau** [comment]
Any updates on this? Thanks for the work on this btw!!

**Comment by Josebaseba** [comment]
Hey, I couldn't find the reason why it happened, I'm not sure whether it was something related with Atlas and their I/O limit or if the problem was in the code. In the graphs it seemed like if I had way more reads/writes than I should (looking to the online users ratio).

My original thought was that the connection was opening too many times or maybe that it wasn't closing, making more requests at the same time, but I couldn't prove it.

I need to test it more deeply. If you could test it locally or against any mongo service maybe we can find what it fails.

**Comment by johnabrams7** [comment]
@Josebaseba We recently discussed this PR and it's still on our radar and are having further examined.

**Comment by luislobo** [comment]
@Josebaseba I'll contact you in private: we should join forces, merge our two PRs. I want to move yours or mine forward. Already talked to people in the Sails team about this. Sending you an email
josebalega@gmail.com

**Comment by luislobo** [comment]
@Josebaseba Were you able to test this PR in your environment? I think you mentioned that you found issues back then (performance?)

**Review by rachaelshaw — COMMENTED** [review]
@luislobo @Josebaseba would you say this is ready to merge? I'll be testing it out today, but let me know if there's anything else you were planning to change

**Comment by luislobo** [comment]
@rachaelshaw Thanks, I've been taking to Mike and we agreed to make it version 2.0.0-0, as there are breaking changes. I'll make these changes today and we can go from there

**Comment by Josebaseba** [comment]
@luislobo @rachaelshaw everything seems good 👍  I couldn't find any performance issue on my latest tests

**Comment by luislobo** [comment]
One thing we could do is update it to the latest mongodb 3.5.x node module: 3.5.10

There is already a 3.6.x but we should handle that upgrade later in a separate PR, as it adds more options.

**Comment by rachaelshaw** [comment]
@luislobo @Josebaseba just published these changes as a prerelease, you can install with `npm install sails-mongo@edge`

**Pull request merged**
