### PR TITLE
[feat] add appName to whitelisted connection options

### PR DESCRIPTION
**Pull request by DominusKelvin**
Resolves https://github.com/balderdashy/sails/issues/7344

### CODE REVIEW

**Review by eashaw — APPROVED** [review]

**Comment by sereisoglu** [comment]
Hi @DominusKelvin, This PR seems to be approved, when can you release a new version?

**Comment by DominusKelvin** [comment]
> Hi @DominusKelvin, This PR seems to be approved, when can you release a new version?

Hey I'm scheduled to do that tomorrow during our open source sync. Thanks for your patience.

**Comment by DominusKelvin** [comment]
Hey @eashaw, this PR has been merged and you can proceed to releasing a patch to NPM. Thank you buddy!

cc @sereisoglu

**Comment by sereisoglu** [comment]
Hey @DominusKelvin, It seems that the new version has not been released, is there a problem?

**Comment by DominusKelvin** [comment]
> Hey @DominusKelvin, It seems that the new version has not been released, is there a problem?

Hey I can see 2.1.2 was released 2 days ago. Can you confirm you've got it?

**Comment by sereisoglu** [comment]
> > Hey @DominusKelvin, It seems that the new version has not been released, is there a problem?
> 
> Hey I can see 2.1.2 was released 2 days ago. Can you confirm you've got it?

Sorry, Yes the new version is out. Thanks! I was checking here: [releases](https://github.com/balderdashy/sails-mongo/releases).

**Comment by DominusKelvin** [comment]
> > > Hey @DominusKelvin, It seems that the new version has not been released, is there a problem?
> 
> > 
> 
> > Hey I can see 2.1.2 was released 2 days ago. Can you confirm you've got it?
> 
> 
> 
> Sorry, Yes the new version is out. Thanks! I was checking here: [releases](https://github.com/balderdashy/sails-mongo/releases).

Oh yeah, I'll cut new release on GH too.

**Pull request merged**
