### PR TITLE
fix(clarifyError): Fixed regexp for E11000

### LINKED ISSUE #336: E11000 Kills server
You are not testing if the match is successfull: https://github.com/balderdashy/sails-mongo/blob/master/lib/utils.js#L183

```
TypeError: Cannot read property '1' of null
    at Object.clarifyError (/Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/utils.js:184:26)
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/adapter.js:280:33
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/collection.js:178:20
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/collection.js:448:20
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/collection.js:547:14
    at resultHandler (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/bulk/ordered.js:412:14)
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at [object Object].Callbacks.emit (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

I think that the regexp is invalid, because message is not starting with E11000:
```
insertDocument :: caused by :: 11000 E11000 duplicate key error index: app.user.$email_1  dup key: { : "somebody@example.com" }
```

### PR DESCRIPTION
**Pull request by Mordred**
This should fix #336

### CODE REVIEW

**Comment by devinivy** [comment]
Thank you!  @dmarcelino @particlebanana have a sec to get this small/important change through?  We released a bug in 0.11.3.

**Comment by mmiller42** [comment]
Interesting. Thanks for the fix! This never happened in my environment, is the error message prefixed with something in other environments?

**Comment by particlebanana** [comment]
Just published `0.11.4`

**Comment by gayanhewa** [comment]
:+1:

**Pull request merged**
