### PR TITLE
Re-apply fix for #177 and add condition for 'datetime' type

### PR DESCRIPTION
**Pull request by mwielbut**
Fix for parsing exception when filtering by date or datetime.

fixes #177 
fixes #1743 in "sails"

### CODE REVIEW

**Comment by phishy** [comment]
+1

**Comment by frankwong** [comment]
+1

**Comment by phishy** [comment]
What is blocking this from being merged?

**Comment by particlebanana** [comment]
Sorry guys, didn't see this. We are looking for more contributors to add to adapters so these things don't sit as long.

**Pull request merged**
