### PR TITLE
Bugfix: Connection is not deleted after connection error

### PR DESCRIPTION
**Pull request by sergioregueira**
As you can see in my commit, if you try to register a connection in your adapter and it fails, it keeps registered in the `connections` object, blocking future retries of register the connection.

```
registerConnection: function(connection, collections, cb) {

  if(connections[connection.identity]) return cb(Errors.IdentityDuplicate);

}
```

This provokes errors to [Waterline](https://github.com/balderdashy/waterline) users, because they receive the error thrown in that line if the first database initialization fails (ie. database was down) and they try to `initialize()` again their databases (ie. database is up again).

### CODE REVIEW

**Comment by mikermcneil** [comment]
Looks good to me, @sergioregueira.  And makes sense.  Would you mind adding a test to verify this and help prevent future regressions?  Best for the test is probably in: https://github.com/balderdashy/sails-mongo/tree/master/test/unit

**Comment by sergioregueira** [comment]
I am sorry, I was very busy. I will add it this weekend, do not close the pull request :)

**Comment by sergioregueira** [comment]
I added the unit test but the build is failing due to external changes not related to my pull request.

**Comment by sergioregueira** [comment]
Can you check it @mikermcneil?

**Comment by sergioregueira** [comment]
I am tired of waiting for this pull request...

**Pull request closed without merging**
