### PR TITLE
CHANGED where/like clause is now case-insensitive

### PR DESCRIPTION
**Pull request by mifkata**

### CODE REVIEW

**Comment by mdconaway** [comment]
This would be a nice feature to merge into main. 

I understand some people may also want the ability to toggle case sensitivity at the adapter or query level. (Which is not solved in this pull request)

What do you think @sgress454 or @mikermcneil ?

**Comment by mikermcneil** [comment]
@clickbuster @mdconaway Hmm, this one is interesting because it's already being implemented via a regexp anyway.  One solution would be a Mongo-specific meta key (e.g. `.meta({makeLikeModifierCaseInsensitiveInMongo: true})`.  Of course, that'd get annoying to type pretty quickly (but it could always be wrapped up in a userland helper.)

Another option would be a more standardized flag.  This'd have the advantage of us being able to boil it up into a model setting (which would mean you'd only have to change one file in your app to switch everything between case-sensitive and case-insensitive like/contains/startsWith/endsWith queries).  

I tracked this in the roadmap [here](https://trello.com/c/GHUSXlV1)

**Comment by clickbuster** [comment]
@mikermcneil I don't see a reason why LIKE shouldn't be case-insensitive, since you can always query with '%search%' to get exactly the same case-sensitive result. Also, in most databases the LIKE functionality, where available, is case-insensitive. The problem with adding a meta, is that it won't be a standard property for every adapter and may cause major issues when switching from one adapter to another.

**Comment by daviddang91** [comment]
This is a great feature. Thanks.

**Comment by luislobo** [comment]
@rachaelshaw This should be closed as it's resolved

**Comment by mifkata** [comment]
@luislobo @rachaelshaw I'm closing the PR in favour of https://github.com/balderdashy/sails/issues/7014#issuecomment-649097225 Thanks

**Pull request closed without merging**
