### PR TITLE
Update README to include version compatibility.

### PR DESCRIPTION
**Pull request by andypham**

### CODE REVIEW

**Comment by particlebanana** [comment]
Thanks @andypham would you be interested in becoming a collaborator on the sails-mongo adapter?

**Comment by andypham** [comment]
@particlebanana Would love to be one. Thanks for the offer.

**Comment by mgenev** [comment]
you should come to this chat @andypham  https://balderdashy.slack.com/messages/sails-contributors/

**Comment by andypham** [comment]
I'm in a meeting right now till 2:30.

**Comment by mgenev** [comment]
Doesn't have to be right now, just in general :)

**Pull request merged**
