### PR TITLE
Remove cloning of ObjectID upon insert, etc.

### PR DESCRIPTION
**Pull request by devinivy**
This fixes an issue around creating records with specified mongo IDs.  In particular, this resolves an error that occurs when attempting to associate records during record creation.  See https://github.com/balderdashy/waterline/issues/908

The cloning step that used to happen here would clone a mongo ObjectId object, which would only happen incompletely due to the object's prototype.  In particular, it had its own `toString` method which was typically used to return the string representation of the mongo id.  Instead, you'd get `[object Object]` as an id!  D'oh!

CC @anasyb @particlebanana

### CODE REVIEW

**Comment by tjwebb** [comment]
Hmm. If this fixes the issue then good, but I'm wondering if the original author had a good reason for using `clone` there...

**Comment by devinivy** [comment]
Good point... I saw that it did actually cause some tests to fail at first.  I fixed that up– seems safe now, but I'm waiting to hear from Travis!

**Comment by dmarcelino** [comment]
Looks good :white_check_mark:

**Comment by anasyb** [comment]
wow... good one @devinivy this solved the issue on my main project... no more error msgs and no more `[Object object]` IDs ending up in join table...

**Comment by dmarcelino** [comment]
@particlebanana, @mgenev, can you guys take a look and eventually merge? Thanks

**Comment by dmarcelino** [comment]
@devinivy, can you merge the latest master to see if it makes it pass the tests? Thanks

**Comment by devinivy** [comment]
Looks like we're all set!

**Comment by dmarcelino** [comment]
:white_check_mark:

**Comment by anasyb** [comment]
hooray :D :D 
awesome!!

**Pull request merged**
